### ISSUE TITLE
ep10 碰到些問題

### ISSUE THREAD

**Issue by Lyndon1983** [m0neyball/bootcamp-laravel#4]
@yuchih 
期間有些問題
在ep10 的 create.blade.php 
1.textfield [tab] 產生出來的templete是 {{}} 而不是 {!! !!} 
2.submitfield [tab] 產生不出教學中的templete

這些不知道是不是因為 illuminate/html 沒裝好所導致

**Comment by yuchih** [comment]
更新一下 PHPStorm config 上次有更新

**Comment by Lyndon1983** [comment]
更新config 解決了

**Comment by Lyndon1983** [comment]
更新config後解決了
